### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by roderik** [feliperazeek/playframework-elasticsearch#26]
I'm new to Play, but this statement seems strange

https://gist.github.com/8316ab565bcf0786772f

**Comment by roderik** [comment]
Fixed it by adding this to my own dependencies file

```
- org.elasticsearch -> elasticsearch 0.17.8
- se.scalablesolutions.akka -> akka-amqp 1.2
```

repositories:
    - elasticsearch:
        type: iBiblio
        root: "http://oss.sonatype.org/content/repositories/releases/"
        contains:
            - org.elasticsearch -> *

```
- akka:
    type: iBiblio
    root: "http://akka.io/repository/"
    contains:
        - se.scalablesolutions.akka -> *
```
